project:
  type: website
  output-dir: "."

website:
  title: "Daniel Noone" 
  navbar:
    pinned: true
    left:
      - text: 'DANL 200 Project'
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: "Data Frames"
        href: data.frames.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>Â© Daniel Noone, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
